# Numpy TEST

1.Explain the difference between copy and view in NumPy arrays.


* Shallow copy creates a new array, but any modifications made to it will affect the original array as well since they share the same data.
* Deep copy creates a completely independent array with its own data; changes in one do not affect the other.

In [2]:
import numpy as np
a = np.array([1, 2, 3])
# shallow copy
shallow_copy = a.view()  
# deep copy
deep_copy = a.copy()     

In [5]:
shallow_copy.base

array([1, 2, 3])

In [7]:
print(deep_copy.base)

None


2.	Explain the difference between array and list?


* List is heterogenouse data structure and values stored in different locations .
* While in array it is homogeneouse data structure and and contiguous memory location.
* Array support elementwise operations so it make array more faster than list

3.	Given an array a = np.array([10, 20, 30]), how do you square every element in the array?


In [8]:
a = np.array([10, 20, 30])
a_squared = np.square(a)
print(a_squared) 


[100 400 900]


4.	How do you create an array of zeros with shape (3, 4)?


In [11]:
zero=np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

5.	Given the 1D array a = np.array([1, 2, 3, 4, 5]), how do you calculate the cumulative sum of the elements?


In [12]:
a = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(a)
print(cumulative_sum)  


[ 1  3  6 10 15]


6.	How do you reverse the elements in a NumPy array a = np.array([1, 2, 3, 4, 5])?


In [13]:
a = np.array([1, 2, 3, 4, 5])
reversed_a = a[::-1]
print(reversed_a)  


[5 4 3 2 1]


7.	How do you find the indices of elements that are greater than 4 in the array a = np.array([1, 2, 3, 4, 5, 6, 7])?


In [14]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
indices = np.where(a > 4)
print(indices) 


(array([4, 5, 6], dtype=int64),)


8.	How do you create a 2D array with random floating-point numbers between 0 and 1 of shape (3, 3)?


In [15]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.05332115 0.14369315 0.12018463]
 [0.60166653 0.64101094 0.04658378]
 [0.28906137 0.45949627 0.83737834]]


9.	Extract the elements at indices [0, 2, 4] from the array a = np.array([10, 20, 30, 40, 50]).


In [19]:
a = np.array([10, 20, 30, 40, 50])
a[[0,2,4]]

array([10, 30, 50])

10.	Given the array a = np.array([10, 20, 30, 40]), how do you normalize the array so that its values are between 0 and 1?


In [17]:
a = np.array([10, 20, 30, 40])
normalized_a = (a - a.min()) / (a.max() - a.min())
print(normalized_a)  


[0.         0.33333333 0.66666667 1.        ]


11.	How do you concatenate two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) along the first axis?


In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concatenated = np.concatenate((a, b), axis=0)
print(concatenated)  

[1 2 3 4 5 6]


12.	How do you find the dot product of two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6])?


In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(dot_product)  


32


13.	How do you create an identity matrix of size 4x4?


In [23]:
identity_matrix=np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

14.	How do you generate an array with random integers between 1 and 100, of shape (4, 4)?


In [24]:
random_int_array = np.random.randint(1, 101, size=(4, 4))
print(random_int_array)


[[13  8 65 70]
 [43 42 13 52]
 [43 88 94 37]
 [23 96 97  7]]


15.	How do you split a NumPy array a = np.array([1, 2, 3, 4, 5, 6]) into three sub-arrays?


In [25]:
a = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.array_split(a, 3)
print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


16.	Given the 2D array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how do you compute the sum of all elements along the second axis?


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_along_axis = np.sum(a, axis=1)
print(sum_along_axis)  


[ 6 15 24]


17.	How do you compute the element-wise maximum of two arrays a = np.array([1, 2, 3]) and b = np.array([3, 2, 1])?


In [27]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
elementwise_max = np.maximum(a, b)
print(elementwise_max) 


[3 2 3]


18.	How do you find the unique elements in the array a = np.array([1, 2, 2, 3, 3, 4, 5])?


In [28]:
a = np.array([1, 2, 2, 3, 3, 4, 5])
unique_elements = np.unique(a)
print(unique_elements)  


[1 2 3 4 5]


19.	How do you use np.arange to create an array of values between 1 and 50 with a step of 3, and then filter the elements that are divisible by 5?


In [30]:
a = np.arange(1, 51, 3)
print(a)
divisible_by_5 = a[a % 5 == 0]
print(divisible_by_5)  

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
[10 25 40]


20.	Given the array a = np.array([1, 2, 3, 4, 5]) and b = np.array([6, 7, 8, 9, 10]), use np.where to replace elements in a that are less than 3 with -3, then  horizontally stack a and b.


In [32]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.where (a<3,-3,a)
print(c)
d=np.hstack((c,b))
print(d)
ab=np.hstack((a,b))
print(ab)

[-3 -3  3  4  5]
[-3 -3  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


21.How do you generate a 3D array of shape (4, 3, 2) where each 2D slice (3x2) is filled with random values between 0 and 1, and then normalize the entire 3D array to values between 0 and 1 (with respect to the min and max of the array)?


In [34]:
arr = np.random.rand(4, 3, 2)
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
normalized_arr

array([[[0.82755054, 0.77452764],
        [0.33405937, 0.        ],
        [0.1989932 , 0.81524068]],

       [[0.93133311, 0.13066597],
        [0.44671828, 0.91599245],
        [0.92891104, 0.84541543]],

       [[0.06995723, 0.37968147],
        [0.73657407, 0.26359941],
        [0.56062958, 0.92919343]],

       [[0.58236787, 0.57864039],
        [1.        , 0.9647102 ],
        [0.7006449 , 0.72032554]]])

22.Given a 2D array of shape (5, 5) filled with random integers between 1 and 100, replace all odd numbers with -1 and all even numbers with 1.


In [35]:
arr = np.random.randint(1, 101, size=(5, 5))
modified_arr = np.where(arr % 2 == 0, 1, -1)
modified_arr

array([[-1, -1,  1,  1, -1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1,  1],
       [-1,  1,  1, -1,  1],
       [ 1,  1,  1,  1, -1]])

23.Given a large 1D array of 10 million random floating-point numbers between 0 and 1, find the 10th and 90th percentile of the values.


In [38]:
large_arr = np.random.rand(10000000)
percentile_10 = np.percentile(large_arr, 10)
percentile_90 = np.percentile(large_arr, 90)
print(percentile_10)
print(percentile_90)

0.09979836541455867
0.9000465465404485


24.	Given a 5x5 matrix arr, use np.where to:

        Replace all elements greater than 10 with the value 100.
        Replace all elements less than or equal to 10 with the value -100


In [43]:
arr = np.random.randint(1, 21, size=(5, 5))
modified_arr = np.where(arr > 10, 100, -100)

print("Original Matrix:\n",arr)
print("\nModified Matrix (with np.where):\n",modified_arr)


Original Matrix:
 [[20 16  4  7  8]
 [ 6 10  6 16 16]
 [ 7  5 20 18 12]
 [ 7 12 17 11  4]
 [19  3 11  7 20]]

Modified Matrix (with np.where):
 [[ 100  100 -100 -100 -100]
 [-100 -100 -100  100  100]
 [-100 -100  100  100  100]
 [-100  100  100  100 -100]
 [ 100 -100  100 -100  100]]


25.	Given a 2D array arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), perform the following operations:
            •	Horizontally split the array into two equal parts.
            •	Vertically split the array into three equal parts.
            •	Stack the split parts vertically and horizontally.


In [44]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
hsplit_arr = np.hsplit(arr, 2)

vsplit_arr = np.vsplit(arr, 3)

vstack_arr = np.vstack(vsplit_arr)

hstack_arr = np.hstack(hsplit_arr)


In [45]:
hsplit_arr

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [46]:
vsplit_arr

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [47]:
vstack_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
hstack_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])