# TASK ONE

In [1]:
import numpy as np

# Question 1 
1.Explain the difference between 1-dimensional, 2-dimensional, and 3-dimensional arrays.



* 1D is a collection of zero dimension 
* An array that has 1-D arrays as its elements is called a 2-D array.
* An array that has 2-D arrays (matrices) as its elements is called 3-D array.

# Question 2
2.Explain the difference between array and list?


* An array is a collection of items stored at contiguous memory locations.
* The idea is to store multiple items of the same type together. 
* arrays store homogeneous data whereas lists may contain heterogeneous data .
* item wise operations are possible in arrays.

# Question 3
3.How do you access elements in a 1-dimensional NumPy array? Provide examples.


In [10]:

give an array and print the index number
a=([12,3,3,44,5])
print(a[3])

44


# Question 4
4.How do you create a 1D NumPy array with values from 0 to 20?


In [18]:
import numpy as np
# use arange() function
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Question 5
5.Given a 1D array arr = np.array([1, 2, 3, 4, 5]), how do you reshape it into a 2x3 array? What error do you get?


In [24]:
a=np.array([1,2,3,4,5])
a.reshape(2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

* The error printed would be that the array cannot be reshaped into (2,3) .

# Question 6
6.How can you access the third element of a 1D array arr = np.array([10, 20, 30, 40, 50])?


In [28]:
arr=np.array([10,20,30,40,50])
print (arr[2])

30


# Question 7
7.How do you access the element at position (1, 2, 2) in array?

In [15]:
a=np.array([[[1,2,3],[5,4,6],[6,2,1]],[[4,3,5],[7,5,6],[2,1,4]],[[8,9,0],[3,4,5],[5,7,9]]])
print (a[1,2,2])

4


# Question 8
8.How do you find the number of dimensions of a NumPy array arr = np.array([[1, 2, 3], [4, 5, 6]])?


In [16]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

# Question 9
9.How do you access the element in the second row and third column of array?


In [18]:
arr=np.array([[1,2,3],[9,7,5]])
print(arr[1,2])

5


# Question 10
10. Create an array with 6 dimensions using a 2D vector with values [1,2,3,4],[5,6,7,8] and verify that last dimension has value 4.


In [20]:
arr=np.array([[1,2,3,4],[5,6,7,8]], ndmin=6)
print(arr)
print(arr.shape)

[[[[[[1 2 3 4]
     [5 6 7 8]]]]]]
(1, 1, 1, 1, 2, 4)


# Question 11
11. How do you modify the last element of array to be 100?


In [21]:
arr=np.array([1,2,3,4,5])
arr[-1]=100
arr


array([  1,   2,   3,   4, 100])

# Question 12
12. Extract all even numbers from the array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).


In [23]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr_2=arr1%2==0
arr1[arr_2]

array([2, 4, 6, 8])

In [ ]:
# Question 13
13. Extract the third element from the array a = np.array([1, 2, 3, 4, 5])


In [102]:

a=np.array([1,2,3,4,5])
print(a[2])

3


# Question 14
14. Given the array a = np.array([1, 2, 3, 4, 5]) and b = np.array([6, 7, 8, 9, 10]), use np.where to replace elements in a that are less than 3 with -3, then  horizontally stack a and b.


In [11]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.where (a<3,-3,a)
print(c)
np.hstack((a,b))

[-3 -3  3  4  5]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Question 15
15.Create an array using np.arange from 0 to 10 with a step of 0.5. Then, use a filter to find all values that are greater than 5. What are the resulting elements?


In [9]:
a=np.arange(0,10,0.5)
print(a)
b=[]
for i in a:
    if i>5:
        b.append(True)
    else:
        b.append(False)
c=a[b]
c

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])