# Question 1
1.Create a 3-D array of shape (2, 3, 4) with random integers between 10 and 50.


In [6]:
import numpy as np
arr=np.random.randint (10,50,24)
print(arr)
arr.reshape(2,3,4)

[13 26 21 13 15 19 48 49 18 41 41 21 17 25 29 31 27 34 26 33 30 15 10 42]


array([[[13, 26, 21, 13],
        [15, 19, 48, 49],
        [18, 41, 41, 21]],

       [[17, 25, 29, 31],
        [27, 34, 26, 33],
        [30, 15, 10, 42]]])

# Question 2
2.Given two arrays, a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division.

In [7]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.add (a,b))
print(np.subtract (a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# Question 3
3.Create a 2-D array of shape (3, 3) with all elements as 1.

In [8]:

a=np.ones((3,3),dtype='int')
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Question 4
4.Reshape the array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) into a 3x3 matrix. Flatten the 3x3 matrix back into a 1-D array.


In [9]:
a=np.array([1,2,3,4,5,6,7,8,9])
a.reshape(3,3)
a.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question 5
5.Stack two arrays vertically and horizontally: a = np.array([[1, 2], [3, 4]]) and b = np.array([[5, 6], [7, 8]]).


In [10]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.vstack ((a,b))
d=np.hstack((a,b))
c,d

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]))

# question 6
6.Split the array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) into two arrays at the 5th element.


In [11]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array_split(a,2)
b

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

# Question 7
7.Extract the second row from the 2-D array a = np. array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).


In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[1]
b

array([4, 5, 6])

# Question 8
8.Extract the elements at indices [0, 2, 4] from the array a = np.array([10, 20, 30, 40, 50]).


In [13]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)
extracted=a[[0,2,4]]
extracted
a[0:5:2]

[10 20 30 40 50]


array([10, 30, 50])

# Question 9
9. Calculate the sum, mean and standard deviation of the array a =    np.array([1, 2, 3, 4, 5]).

In [17]:
a=np.array([1,2,3,4,5])
print(np.mean(a))
print(np.sum(a))
print(np.std(a))

3.0
15
1.4142135623730951


# Question 10
10. Find the maximum and minimum values in the 2-D array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) along both axes.


In [19]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.max(a,axis=0)
b=np.max(a,axis=1)
d=np.min(a,axis=0)
e=np.min(a,axis=1)
print(c)
print(b)
print(d)
print(e)

[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]


# Question 11
11. Given the 2-D arrays a = np.array([[3, 1, 4], [1, 5, 9]]) and b = np.array([[2, 6, 5], [7, 8, 0]]), sort each array, then horizontally stack the sorted arrays.


In [20]:
a=np.array([[3,1,4],[1,5,9]])
b=np.array([[2,6,5],[7,8,0]])
c=np.sort(a)
d=np.sort(b)
print(np.hstack((a,b)))

[[3 1 4 2 6 5]
 [1 5 9 7 8 0]]


# Question 12
12. Given the array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), use np.where to find the indices of elements that are either less than 3 or greater than 7.

In [21]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.where(a<3))
print(np.where(a>7))

(array([0, 1], dtype=int64),)
(array([7, 8, 9], dtype=int64),)


# Question 13
13. Given a 2-D array representing daily temperatures of two cities over a   week: a = np.array([[30, 32, 31, 29, 28, 30, 31], [25, 26, 27, 28, 29, 30, 31]]), use np.where to find the days where the temperature was above 30 degrees in both cities. Then, horizontally stack the temperature data for both cities.


In [22]:
import numpy as np

a = np.array([[30, 32, 31, 29, 28, 30, 31], 
              [25, 26, 27, 28, 29, 30, 31]])

mask = (a[0] > 30) & (a[1] > 30)
mask

days_above_30 = np.where(mask)
days_above_30

filtered_a = a[:, mask]
filtered_a

stacked_data = np.hstack(filtered_a)
stacked_data

array([31, 31])

# Question 14
14. Given two arrays representing daily closing prices of two stocks over a month: a = np.array([[100, 101, 102, 103, 104], [200, 201, 202, 203, 204]]), calculate the daily returns (percentage change), replace negative returns with 0 using np.where, and vertically stack the processed data with the original prices.

In [25]:
import numpy as np

# Define the arrays
a = np.array([[100, 101, 102, 103, 104],
              [200, 201, 202, 203, 204]])


#### Daily return for a day can be calculated as:

Return= ((Price today-Price yesterday)/Price yesterday)×100


In [26]:
# Calculate daily returns
daily_returns = np.diff(a, axis=1) / a[:, :-1] * 100
daily_returns

np.diff(a, axis=1) #computes the differences between consecutive elements along each row

a[:, :-1] #The slice a[:, :-1] selects all rows (:) and all columns except the last one (:-1).

# Replace negative returns with 0
processed_returns = np.where(daily_returns < 0, 0, daily_returns)
processed_returns


array([[1.        , 0.99009901, 0.98039216, 0.97087379],
       [0.5       , 0.49751244, 0.4950495 , 0.49261084]])

In [27]:
# Pad the returns arrays with a leading zero
# creates a 2x1 array of zeros 
b=np.zeros((a.shape[0], 1))
b

array([[0.],
       [0.]])

In [28]:
padded_processed_returns = np.hstack((b,processed_returns))
padded_processed_returns


array([[0.        , 1.        , 0.99009901, 0.98039216, 0.97087379],
       [0.        , 0.5       , 0.49751244, 0.4950495 , 0.49261084]])

In [29]:
# Vertically stack the original prices with the processed returns
stacked_data = np.vstack((a, padded_processed_returns))
stacked_data


array([[100.        , 101.        , 102.        , 103.        ,
        104.        ],
       [200.        , 201.        , 202.        , 203.        ,
        204.        ],
       [  0.        ,   1.        ,   0.99009901,   0.98039216,
          0.97087379],
       [  0.        ,   0.5       ,   0.49751244,   0.4950495 ,
          0.49261084]])

# Question 15
15. Create a filter array that will return only divisible by 3 elements from the original array

In [24]:
a=np.arange(1,30)
arr=[]
for i in a:
    if i%3==0:
        arr.append(True)
    else:
        arr.append (False)
array=a[arr]
array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])